version: '3'
services:

  mediator:
    image: indicio-tech/aries-mediator
    hostname: mediator
    restart: unless-stopped
    environment:
      - DEPLOYMENT_ENV=TEST
      - AGENT_NAME=mediator-test
      - WALLET_NAME=test-1
      - HTTP_ENDPOINT=http://localhost:3007
      - WS_ENDPOINT=ws://localhost:3008 
      - HTTP_PORT=3007
      - WS_PORT=3008
      - RDBMS_URL=db:5432
      - RDBMS_AUTH={"account":"development","password":"development","admin_account":"development","admin_password":"development"}
    volumes:
      - ./wait-for-it:/home/indy/wait-for-it
    command: >
      sh -c "./wait-for-it/wait-for-it.sh db:5432 -s -t 60 -- bash ./startup"
    ports: 
      - "3007:3007"
      - "3008:3008"
    depends_on:
      - "db"
    networks:
      - mediator-network

  # DB Service
  db:
    image: postgres:9.5
    hostname: db
    restart: always
#    ports: # Uncomment to access postgres outside of containers
#      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data:consistent
    environment:
      POSTGRES_USER: development
      POSTGRES_PASSWORD: development
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - mediator-network

#Docker Networks
networks:
  mediator-network:
    driver: bridge


