version: '3'
services:

  ngrok-mediator-http:
    image: wernight/ngrok
    command: ngrok http mediator:3007 --log stdout
    networks:
      - mediator-network

  ngrok-mediator-ws:
    image: wernight/ngrok
    command: ngrok http mediator:3008 --log stdout
    networks:
      - mediator-network

  mediator:
    image: indicio-tech/aries-mediator
    hostname: mediator
    restart: unless-stopped
    environment:
      - NGROK_HTTP=ngrok-mediator-http
      - NGROK_WS=ngrok-mediator-ws
      - DEPLOYMENT_ENV=TEST
      - AGENT_NAME=mediator-test
      - WALLET_NAME=test-1
      - WALLET_KEY=testkey
      - HTTP_PORT=3007
      - WS_PORT=3008
      - RDBMS_URL=db:5432
      - RDBMS_AUTH={"account":"development","password":"development","admin_account":"development","admin_password":"development"}
    volumes:
      - ./ngrok-wait-http.sh:/home/indy/ngrok-wait-http.sh
      - ./ngrok-wait-ws.sh:/home/indy/ngrok-wait-ws.sh
      - ./wait-for-it:/home/indy/wait-for-it
    command: >
      sh -c "./ngrok-wait-http.sh ./ngrok-wait-ws.sh ./wait-for-it/wait-for-it.sh db:5432 -s -t 60 -- bash ./startup"
    ports: 
      - "3007:3007"
      - "3008:3008"
    depends_on:
      - "db"
    networks:
      - mediator-network

  # DB Service
  db:
    image: postgres:9.5
    hostname: db
    restart: always
#    ports: # Uncomment to access postgres outside of containers
#      - "5432:5432"
    environment:
      POSTGRES_USER: development
      POSTGRES_PASSWORD: development
    networks:
      - mediator-network

#Docker Networks
networks:
  mediator-network:
    driver: bridge


